### ISSUE TITLE
Revamp the Readme

### ISSUE THREAD

**Issue by Roxie-32** [Caesarsage/OSS-Contribution-Beginer#7]
The  Readme file has a few grammatical errors. It is also not easy to understand the purpose of this repo at first glance. I want to make the ReadMe more structured and easy to understand , while retaining the information it contains.

**Comment by Caesarsage** [comment]
This is a good issue, you can assign to yourself and make a PR

**Comment by Roxie-32** [comment]
I am closing this issue. If anyone wants to make updates to the readme they can create an issue that explains the problem and what they will like to work on in the readme.

it is easier to track this way.
